name: Broken link check
on:
  schedule:
    - cron: 0 0 1 * * # run monthly
  repository_dispatch: # run manually
    types: [check-link]
  push: # for test

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Check for broken links
        id: link-report
        uses: celinekurpershoek/link-checker@v1.0.2
        with:
          # Required:
          url: "https://pyrsia.io/"
          # optional:
          honorRobotExclusions: false
          ignorePatterns: 'https://latex.codecogs.com,https://crates.io'
          recursiveLinks: true
      - name: Get the result
        run: echo "${{steps.link-report.outputs.result}}"
