name: Broken link check
on:
  schedule:
    - cron: 0 0 1 * * # run monthly
  repository_dispatch: # run manually
    types: [check-link]
  push: # for test

jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://pyrsia.io/
          cmd_params: "--max-connections=3 --color=always"  # Refer to https://github.com/raviqqe/muffet/blob/main/arguments.go
